import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Jumbotron from '../components/Jumbotron/Jumbotron'
import DefaultLayout from '../layouts/Default'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Guns | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <DefaultLayout>
      < Jumbotron />
      </DefaultLayout>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
