import Head from 'next/head';
import React, { useState, useEffect } from 'react'
import { useRouter } from 'next/router'
import DefaultLayout from '../../layouts/Default';

export default function Gun() {

    const [gun, setGun] = useState(null);


    const router = useRouter();
    const { id } = router.query;

    const fetchGun = async () => {
        const response = await fetch(`/api/guns/${id}`);
        const data = await response.json();
        setGun(data);
    }

    useEffect(() => {
        fetchGun();
    }, []);


    return (
        <div>
            <Head>
                <title>Guns | {gun && gun.name}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <DefaultLayout>
                {gun && (
                    <div className="container mt-5 flex">
                        <img className="card-img" src={gun.image.url} alt={gun.image.alt} />
                        <div className="card-body">
                            <h3>{gun.name}</h3>
                            <p>{gun.phone}</p>
                            <p>{gun.email}</p>
                            <p>{gun.description}</p>
                        </div>
                    </div>
                )
                }
            </DefaultLayout>
        </div>
    )
}